import request from "@/servers/useRequest";
import { RequestResponse, VoidRequestResponse } from "@/types/interfaces/request";
import { SandboxListResponse } from "@/types/interfaces/sandbox";

/**
 * 获取沙盒列表
 */
export const apiGetSandboxList = async (): Promise<
  RequestResponse<SandboxListResponse>
> => {
  const res = await request({
    url: "/api/sandbox/config/select/list",
    method: "GET",
  });
  return res;
};

/**
 * 更新选中的沙盒
 */
export const apiUpdateSelectedSandbox = async (
  agentId: string,
  sandboxId: string,
): Promise<VoidRequestResponse> => {
  const res = await request({
    url: `/api/sandbox/config/selected/${agentId}/${sandboxId}`,
    method: "POST",
  });
  return res;
};

/**
 * 重启智能体
 */
export const apiRestartAgent = async (
  conversationId: number,
): Promise<VoidRequestResponse> => {
  const res = await request({
    url: `/api/computer/agent/stop/${conversationId}`,
    method: "POST",
  });
  return res;
};

/**
 * 重启容器
 */
export const apiRestartSandbox = async (
  conversationId: number,
): Promise<VoidRequestResponse> => {
  const res = await request({
    url: `/api/computer/pod/restart?cId=${conversationId}`,
    method: "POST",
  });
  return res;
};
