import request from '@/servers/useRequest';
import { RequestResponse, Page } from '@/types/interfaces/request';
import { SkillListForAtParams, SkillInfoForAt } from '@/types/interfaces/skill';

// 全部技能列表
export async function apiSkillListForAt(data: SkillListForAtParams): Promise<RequestResponse<Page<SkillInfoForAt>>> {
  const res = await request({
    url: '/api/published/skill/list-for-at',
    method: 'POST',
    data
  });
  return res;
}

// 最近使用的技能列表
export async function apiSkillRecentlyUsedList(data: any): Promise<RequestResponse<SkillInfoForAt[]>> {
  const res = await request({
    url: '/api/published/skill/recentlyUsed/list',
    method: 'POST',
    data
  });
  return res;
}

// 已收藏的技能列表
export async function apiSkillCollectList(data: any): Promise<RequestResponse<SkillInfoForAt[]>> {
  const res = await request({
    url: '/api/published/skill/collect/list',
    method: 'POST',
    data
  });
  return res;
}
