import { getApiBaseUrl } from './config';

// 文件上传地址
export const getUploadFileAction = (): string => getApiBaseUrl() + '/api/file/upload';

// 会话 Connection地址
export const getConversationConnectionUrl = (isTemp: boolean): string =>
  getApiBaseUrl() + (isTemp ? '/api/temp/chat/completions' : '/api/agent/conversation/chat');

// 文档地址
export const DOCUMENT_URL = 'https://nlp-book.swufenlp.group';

// 平台文档地址
export const SITE_DOCUMENT_URL = 'https://nuwax.com/user-manual.html';

// 可上传文件后缀类型：doc docx pdf md json txt
export const UPLOAD_FILE_SUFFIX = ['doc', 'docx', 'pdf', 'md', 'json', 'txt'];

// 验证码长度
export const VERIFICATION_CODE_LEN = 6;

// 倒计时
export const COUNT_DOWN_LEN = 60;

// 默认图片数量
export const DEFAULT_IMAGE_COUNT = 9;
// 默认文件数量
export const DEFAULT_FILE_COUNT = 9;

// 临时会话的uid, 用于区分临时会话和普通会话, 缓存在sessionStorage中，key为TEMP_CONVERSATION_UID, value为uid
export const TEMP_CONVERSATION_UID = 'TEMP_CONVERSATION_UID';
// 临时会话的key
export const TEMP_CHAT_KEY = 'TEMP_CHAT_KEY';

// 全部
export const CONST_ALL = 'All';

// 聊天输入方式
export const CHAT_INPUT_METHOD = 'CHAT_INPUT_METHOD';

// Agent 模式（Yolo / Ask）
export const AGENT_MODE = 'AGENT_MODE';


// 公共 header 配置
export const COMMON_HEADERS = {
    'Content-Type': 'application/json',
    // #ifdef MP-WEIXIN
    'X-Client-Type': 'mp-weixin',
    // #endif
}
