// 环境配置
// 使用uni-app的条件编译来处理不同环境
let API_BASE_URL = '';

// uEnvProd
if (process.env.NODE_ENV === 'production') {
     API_BASE_URL = '';
}

// uEnvDev
if (process.env.NODE_ENV === 'development') {
	 API_BASE_URL = 'https://testagent.xspaceagi.com';
}

// 允许外部链接跳转的域名
export const ALLOW_EXTERNAL_LINK_DOMAIN = ['https://testagent.xspaceagi.com'];

export { API_BASE_URL, ALLOW_EXTERNAL_LINK_DOMAIN };
