import { ref } from 'vue'
import type { AgentDetailDto, AgentManualComponentInfo } from '@/types/interfaces/agent'
import { BindConfigWithSub } from '@/types/interfaces/common'
import { MessageInfo, ConversationInfo, ProcessingInfo } from '@/types/interfaces/conversationInfo'

/**
 * 数据层：负责状态管理和数据存储
 */
export default class AgentDetailData {
	// 基础信息
	agentId = ref<number | null>(null)
	agentName = ref<string>('')
	agentInfo = ref<AgentDetailDto | null>(null)
	conversationId = ref<number | null>(null)
	
	// 消息相关
	messageList = ref<MessageInfo[]>([])
	chatSuggestList = ref<string[]>([])
	requestId = ref<string>('') 
	messageIdRef = ref<string>('')
	// 当前会话消息请求ID
	currentConversationRequestId = ref<string>('')
	// 停止操作是否正在进行中
	isStoppingConversation = ref<boolean>(false)
	
	// 会话状态
	conversationInfo = ref<ConversationInfo | null>(null)
	// 是否用户问题建议
	isSuggest = ref<boolean>(false)
	// 是否需要更新主题
	needUpdateTopicRef = ref<boolean>(true)
	// 是否正在加载会话
	isLoadingConversation = ref<boolean>(false)
	// 会话是否正在进行中（有消息正在处理）
	isConversationActive = ref<boolean>(false)
	// 是否发送过消息,如果是,则禁用变量参数
	isSendMessageRef = ref<boolean>(false)
	// 是否禁用发送按钮
	wholeDisabled = ref<boolean>(false)
	
	// 组件和功能
	manualComponents = ref<AgentManualComponentInfo[]>([])
	// 已选组件列表
	selectedComponents = ref<AgentSelectedComponentInfo[]>([])
	// 变量参数
	variables = ref<BindConfigWithSub[]>([])
	// 用户填充变量
	userFillVariables = ref<{ [key: string]: string | number }>({})
	// 必填变量参数name列表
	requiredNameList = ref<string[]>([])
	processingList = ref<ProcessingInfo[]>([])
	messageRefs = ref<{ [key: string]: any }>({})
	
	// 滚动相关
	scrollIntoView = ref<string>('')
	scrollInBottom = ref<boolean>(true)
	scrollWithAnimation = ref<boolean>(false)
	scrollTouch = ref<boolean>(false)
	scrolling = ref<boolean>(false)
	keyboardHeight = ref<number>(0)
	
	// 弹窗引用
	refMorePopup = ref<any>(null)
	
	sseProcessor: any = null
	autoToLastMsg = ref<boolean>(false)
	scrollingT = ref<number>(0)
	mouseScroll = ref<boolean>(false)
	needSetLockAutoToLastMsg = ref<boolean>(true)
}
