#!/usr/bin/env bash
# 统一导出 Android 离线编译环境（JAVA_HOME / ANDROID_HOME / wrapper jar）
# 由 setup_sdk.sh / build_device_base.sh 调用，也可: source scripts/android-esp/ensure_env.sh
set -euo pipefail

# JDK：优先 Android Studio JBR，其次 Homebrew OpenJDK 17
if [[ -z "${JAVA_HOME:-}" ]] || [[ ! -x "${JAVA_HOME}/bin/java" ]]; then
  if [[ -x "/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java" ]]; then
    export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
  elif [[ -x "/opt/homebrew/opt/openjdk@17/bin/java" ]]; then
    export JAVA_HOME="/opt/homebrew/opt/openjdk@17"
  elif [[ -x "/opt/homebrew/opt/openjdk/bin/java" ]]; then
    export JAVA_HOME="/opt/homebrew/opt/openjdk"
  fi
fi
if [[ -n "${JAVA_HOME:-}" ]]; then
  export PATH="$JAVA_HOME/bin:$PATH"
fi

# Android SDK：优先已装完整包的工作区路径
if [[ -z "${ANDROID_HOME:-}" ]] || [[ ! -d "${ANDROID_HOME}/platforms" ]]; then
  if [[ -d "/Users/apple/workspace/Android/sdk/platforms" ]]; then
    export ANDROID_HOME="/Users/apple/workspace/Android/sdk"
  elif [[ -d "$HOME/Library/Android/sdk/platforms" ]]; then
    export ANDROID_HOME="$HOME/Library/Android/sdk"
  fi
fi
export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}"

ensure_gradle_wrapper_jar() {
  local proj="${1:-}"
  [[ -n "$proj" ]] || return 0
  local jar="$proj/gradle/wrapper/gradle-wrapper.jar"
  local props="$proj/gradle/wrapper/gradle-wrapper.properties"
  if [[ -f "$jar" ]] && [[ -s "$jar" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$jar")"
  echo "补齐 gradle-wrapper.jar → $jar"
  # DCloud SDK zip 常缺二进制 jar；从 Gradle 官方仓库拉取
  local ver="8.14.3"
  if [[ -f "$props" ]]; then
    ver="$(sed -n 's/.*gradle-\([0-9.]*\)-bin.zip.*/\1/p' "$props" | head -1)"
    ver="${ver:-8.14.3}"
  fi
  curl -L --fail -o "$jar" \
    "https://raw.githubusercontent.com/gradle/gradle/v${ver}/gradle/wrapper/gradle-wrapper.jar"
}

write_local_properties() {
  local proj="${1:-}"
  [[ -n "$proj" && -n "${ANDROID_HOME:-}" ]] || return 0
  local lp="$proj/local.properties"
  # 转义路径中的空格等
  local sdk_escaped
  sdk_escaped="$(printf '%s' "$ANDROID_HOME" | sed 's/:/\\:/g')"
  cat >"$lp" <<EOF
## Generated by ensure_env.sh — do not commit secrets
sdk.dir=${sdk_escaped}
EOF
  echo "✓ local.properties sdk.dir=$ANDROID_HOME"
}

if [[ "${BASH_SOURCE[0]:-}" == "${0}" ]]; then
  echo "JAVA_HOME=${JAVA_HOME:-"(unset)"}"
  echo "ANDROID_HOME=${ANDROID_HOME:-"(unset)"}"
  java -version 2>&1 | head -1 || true
fi
