import request from './useRequest';
import { RequestResponse } from '../types/interfaces/request';
import { TenantConfigInfo,UserInfo} from '../types/interfaces/login';

// 租户配置信息查询接口
export function apiTenantConfig(){
	return request<RequestResponse<TenantConfigInfo>>({
		url: '/api/tenant/config',
		method: 'GET',
	});
}


// 查询当前登录用户信息
export function apiUserInfo() {
  return request<RequestResponse<UserInfo>>({
    url: '/api/user/getLoginInfo',
    method: 'GET',
  });
}