import request from "./useRequest";
import { RequestResponse, VoidRequestResponse } from "../types/interfaces/request";
import type {
  BindEmailParams,
  CodeLogin,
  ILoginResult,
  LoginFieldType,
  ResetPasswordParams,
  SendCode,
  SetPasswordParams,
  TenantConfigInfo,
  UserInfo,
  UserUpdateParams,
  WechatLoginParams,
} from "@/types/interfaces/login";

// 租户配置信息查询接口
export async function apiTenantConfig(): Promise<RequestResponse<TenantConfigInfo>> {
  const res = await request({
    url: "/api/tenant/config",
    method: "GET",
  });
  return res;
}

// 查询当前登录用户信息
export async function apiUserInfo(): Promise<RequestResponse<UserInfo>> {
  const res = await request({
    url: "/api/user/getLoginInfo",
    method: "GET",
  });
  return res;
}

// 微信登录
export async function apiWechatLogin(data: WechatLoginParams): Promise<RequestResponse<ILoginResult>> {
  const res = await request({
    url: "/api/user/mp/codeLogin",
    method: "POST",
    data,
  });
  return res;
}

// 账号密码登录
export async function apiLogin(data: LoginFieldType): Promise<RequestResponse<ILoginResult>> {
  const res = await request({
    url: "/api/user/passwordLogin",
    method: "POST",
    data,
  });
  return res;
}

// 发送验证码
export async function apiSendCode(data: SendCode): Promise<VoidRequestResponse> {
  const res = await request({
    url: "/api/user/code/send",
    method: "POST",
    data,
  });
  return res;
}

// 验证码登录/注册接口
export async function apiLoginCode(data: CodeLogin): Promise<RequestResponse<ILoginResult>> {
  const res = await request({
    url: "/api/user/codeLogin",
    method: "POST",
    data,
  });
  return res;
}

// 首次登录设置密码
export async function apiSetPassword(data: SetPasswordParams): Promise<VoidRequestResponse> {
  const res = await request({
    url: "/api/user/password/set",
    method: "POST",
    data,
  });
  return res;
}

// 退出登录接口
export async function apiLogout(): Promise<VoidRequestResponse> {
  const res = await request({
    url: "/api/user/logout",
    method: "GET",
  });
  return res;
}

// 获取动态认证码
export async function apiUserDynamicCode(): Promise<RequestResponse<string>> {
  const res = await request({
    url: "/api/user/dynamicCode",
    method: "GET",
  });
  return res;
}
