import type {
  ConversationChatSuggestParams,
  ConversationCreateParams,
  ConversationInfo,
  ConversationListParams,
} from '@/types/interfaces/conversationInfo';
import type { RequestResponse } from '@/types/interfaces/request';
import request from '@/servers/useRequest';


// 查询用户历史会话
export function apiAgentConversationList(data: ConversationListParams) {
  return request<RequestResponse<ConversationInfo[]>>({
    url: '/api/agent/conversation/list',
    method: 'POST',
    data,
  });
}


