import request from './useRequest';
import { RequestResponse } from '@/types/interfaces/request';
import { HomeAgentCategoryInfo } from '@/types/interfaces/agentConfig';
import type { ListParams, PageParams } from '@/types/interfaces/common';
import type {
  AgentAkDeleteParams,
  AgentAkUpdateParams,
  AgentDetailDto,
  AgentInfo,
  AgentLogDetailParams,
  apiAgentLogListParams,
  logInfo,
  UserApiKeyInfo,
} from '@/types/interfaces/agent';
import { ACCESS_TOKEN } from '@/constants/home.constants';

// 主页智能体列表接口 - 数据列表查询
export async function apiHomeCategoryList() {
  return request<RequestResponse<HomeAgentCategoryInfo>>({
    url: '/api/home/list',
    method: 'GET',
  });
}


// 已发布的智能体详情接口
export function apiPublishedAgentInfo(agentId: number, withConversationId?: boolean = false) {
  return request<RequestResponse<AgentDetailDto>>({
    url: `/api/published/agent/${agentId}`,
    method: 'GET',
    data: {
      withConversationId
    }
  });
}

// 查询用户最近使用过的智能体列表
export function apiUserUsedAgentList(params: ListParams){
  const {size, pageIndex, keyword} = params;
  // 对关键词进行编码
  const _keyword = keyword ? `&kw=${encodeURIComponent(keyword)}` : '';
  return request<RequestResponse<AgentInfo[]>> ({
    url: `/api/user/agent/used/list/${size}?pageIndex=${pageIndex}${_keyword}`,
    method: 'GET',
  });
}

// 删除用户最近智能体使用记录
export function apiUserUsedAgentDelete(agentId: number) {
  return request<RequestResponse<null>>({
    url: `/api/user/agent/used/delete/${agentId}`,
    method: 'POST',
  });
}

// 智能体收藏
export function apiCollectAgent(agentId: number) {
  return request<RequestResponse<null>>({
    url: `/api/user/agent/collect/${agentId}`,
    method: 'POST',
  });
}

// 智能体取消收藏
export function apiUnCollectAgent(agentId: number)  {
  return request<RequestResponse<null>>({
    url: `/api/user/agent/unCollect/${agentId}`,
    method: 'POST',
  });
}


// 页面请求结果回写
export function apiAgentComponentPageResultUpdate(data: ApiAgentConversationChatPageResultParams)  {
  return request<RequestResponse<null>>({
    url: '/api/agent/conversation/chat/page/result',
    method: 'POST',
    data,
  });
}

// 创建用户临时票据
export function apiUserTicketCreate(){
  const accessToken = uni.getStorageSync(ACCESS_TOKEN) || ''
  return request<RequestResponse<string>>({
    url: '/api/user/ticket/create',
    method: 'POST',
    data:{
      token: accessToken
    },
  });
}