import request from "./useRequest";
import type { RequestResponse, VoidRequestResponse } from "@/types/interfaces/request";

/** 查询当前用户的系统消息列表。 */
export async function apiNotifyMessageList(data: UTSJSONObject): Promise<RequestResponse<any>> {
  return await request({
    url: "/api/notify/message/list",
    method: "POST",
    data,
  });
}

/** 查询当前用户的未读系统消息数量。 */
export async function apiNotifyMessageUnreadCount(): Promise<RequestResponse<number>> {
  return await request({
    url: "/api/notify/message/unread/count",
    method: "GET",
  });
}

/** 将当前用户全部系统消息置为已读。 */
export async function apiNotifyMessageUnreadClear(): Promise<VoidRequestResponse> {
  return await request({
    url: "/api/notify/message/unread/clear",
    method: "GET",
  });
}
