import { Page, RequestResponse } from '../types/interfaces/request';
import { SquarePublishedListParams, SquarePublishedItemInfo, SquareCategoryInfo } from '../types/interfaces/square';
import request from './useRequest';
import { AgentDetailDto } from '../types/interfaces/agent';

// 广场-已发布智能体列表接口
export async function apiPublishedAgentList(
  data: SquarePublishedListParams,
): Promise<RequestResponse<Page<SquarePublishedItemInfo>>> {
  const res = await request({
    url: '/api/published/agent/list',
    method: 'POST',
    data,
  });
  return res as RequestResponse<Page<SquarePublishedItemInfo>>;
}

// 获取广场分类列表
export async function apiPublishedCategoryList(): Promise<RequestResponse<SquareCategoryInfo[]>> {
  const res = await request({
    url: '/api/published/category/list',
    method: 'GET',
  });
  return res as RequestResponse<SquareCategoryInfo[]>;
}

// 获取已发布的智能体详情
export async function apiSquareAgentDetail(
  agentId: number,
): Promise<RequestResponse<AgentDetailDto>> {
  const res = await request({
    url: `/api/published/agent/${agentId}`,
    method: 'GET',
  });
  return res as RequestResponse<AgentDetailDto>;
}
