import { RequestResponse } from "../types/interfaces/request";
import {
  MySubscriptionData,
  CreditSummaryInfo,
  CreditPackageInfo,
  CreditBatchItem,
  SystemSubscriptionPlan,
} from "../types/interfaces/subscription";
import request from "./useRequest";

export async function apiGetMySubscription(params: Record<string, string>) {
  return request<RequestResponse<MySubscriptionData>>({
    url: "/api/subscription/my",
    method: "GET",
    data: params,
  });
}

export async function apiGetCreditSummary() {
  return request<RequestResponse<CreditSummaryInfo>>({
    url: "/api/credit/summary",
    method: "GET",
  });
}

export async function apiListSystemSubscriptionPlans() {
  return request<RequestResponse<SystemSubscriptionPlan[]>>({
    url: "/api/subscription/system/plans",
    method: "GET",
  });
}

export async function apiListCreditPackages() {
  return request<RequestResponse<CreditPackageInfo[]>>({
    url: "/api/credit/package/list",
    method: "GET",
  });
}

export async function apiCreateCreditOrder(data: Record<string, number>) {
  return request<RequestResponse<any>>({
    url: "/api/credit/order/create",
    method: "POST",
    data,
  });
}

export async function apiGetCreditBatches(params: Record<string, string>) {
  return request<RequestResponse<CreditBatchItem[]>>({
    url: "/api/credit/batches",
    method: "GET",
    data: params,
  });
}

export async function apiCreateSubscriptionOrder(data: Record<string, any>) {
  return request<RequestResponse<any>>({
    url: "/api/subscription/order/create",
    method: "POST",
    data,
  });
}

export async function apiGetOrderCashier(orderId: number) {
  return request<RequestResponse<string>>({
    url: "/api/bill/order/pay/cashier",
    method: "GET",
    data: { orderId },
  });
}
