import { AgentComponentTypeEnum } from '../enums/agent';
import type {
  AgentStatisticsInfo,
  CreatorInfo,
} from './agent';

// 智能体分类信息
export interface CategoryInfo {
  name: string;
  type: string;
}

// 智能体分类项详细信息
export interface CategoryItemInfo {
  targetType: AgentComponentTypeEnum;
  targetId: number;
  name: string;
  description: string;
  icon: string;
  statistics: AgentStatisticsInfo;
  publishUser: CreatorInfo;
  collect: boolean;
}

// 主页智能体分类列表
export interface HomeAgentCategoryInfo {
  // 首页分类
  categories: CategoryInfo[];
  // 首页分类数据列表
  categoryItems: {
    [key: string]: CategoryItemInfo[];
  };
}
